# Copyright Thomas Helander. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: 3D Printing
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.0.0-rc1
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.x
description: Prometheus exporter for Prusa3D printers - supports Prusa Link API and Syslog metrics as well as logs from printer.
home: https://prusa3d.com/
icon: https://backend.prusa3d.com/cdn-cgi/image/width=750,format=auto,quality=85/wp-content/uploads/prusaresearch-logo-rgb-black-1-800x451.png
maintainers:
  - name: Tom Helander
    url: https://github.com/thelande/charts
name: prusa-exporter
sources:
  - https://github.com/thelande/charts/tree/main/charts/prusa-exporter
  - https://github.com/pubeldev/prusa_exporter
version: 0.2.1
