# Copyright Thomas Helander. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

prusa-exporter:
  image:
    repository: docker.io/pubeldev/prusa_exporter
    #tag:

  resources: {}

  # -- List of printers to scrape.
  printers: []
  ## - name: <your printer name>  # optional, only used for Grafana dashboard
  ##   type: MINI  # MINI / MK35 / MK35S / MK39 / MK39S / MK4 / MK4S / XL / IX / Core One / Core One L
  ##   address: <ip address of printer>
  ##   username: maker
  ##   password: <password>

  # -- Existing secret containing the above printers configuration.
  printersSecret: ""

  prusalinkScrapeTimeout: 5

  # -- Preset IP address for the UDP service load balancer.
  udpServiceLoadBalancerIP: ""

  # -- Define the IP of the system where the exporter is running. This ensures
  # the correct metrics host is used by the exporter.
  udpIPOverride: ""

  # -- Enable automatic enabling of UDP metrics.
  # Note: When enabled, after starting the exporter your printer will ask to
  # "print" a file named "enable_udp_metrics.gcode". Simply start the "print"
  # to proceed.
  enabledUDPMetrics: true

  # -- URL of your Loki instance. Used to expose the PNG image of the print. (optional)
  lokiPushURL: ""

metrics:
  # -- Enable the service monitor
  enabled: false
  prusalink:
    interval: 60s
  udp:
    interval: 1s
