# Copyright Thomas Helander. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##
global:
  # -- Global Docker image registry
  imageRegistry: ""
  ## e.g:
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  
  # -- Global Docker registry secret names as an array
  imagePullSecrets: []

  # -- Global default StorageClass for Persistent Volume(s)
  defaultStorageClass: ""

  ## Security parameters
  ##
  security:
    # -- Allows skipping image verification
    allowInsecureImages: false

## Common parameters
##
# -- Override Kubernetes version
kubeVersion: ""
# -- Override Kubernetes API versions reported by .Capabilities
apiVersions: []
# -- String to partially override common.names.name
nameOverride: ""
# -- String to fully override common.names.fullname
fullnameOverride: ""
# -- String to fully override common.names.namespace
namespaceOverride: ""
# -- Labels to add to all deployed objects
commonLabels: {}
# -- Annotations to add to all deployed objects
commonAnnotations: {}
# -- Kubernetes cluster domain name
clusterDomain: cluster.local

## Diagnostic mode
diagnosticMode:
  # -- Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  enabled: false
  # -- Command to override all containers in the chart release
  command:
    - sleep
  # -- Args to override all containers in the chart release
  args:
    - infinity

prusaExporter:
  image:
    # -- prusaExporter image registry
    registry: docker.io
    # -- prusaExporter image repository
    repository: pubeldev/prusa_exporter
    # -- prusaExporter image tag
    tag: 2.0.0-alpha2
    # -- The image pull policy
    # ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    pullPolicy: IfNotPresent
    # -- Image pull secrets
    # Secrets must be manually created in the namespace.
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    pullSecrets: []
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
  
  # -- Number of prusaExporter replicas to deploy
  replicaCount: 1

  # -- List of ports for prusaExporter containers
  containerPorts:
    - name: http
      containerPort: 10009
      protocol: TCP
    - name: prusalink
      containerPort: 8514
      protocol: UDP
  ## e.g:
  ## containerPorts:
  ##   - name: myservice
  ##     containerPort: 9090
  ##

  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  livenessProbe:
    # -- Enable livenessProbe on prusaExporter containers
    enabled: true
    # -- Initial delay seconds for livenessProbe
    initialDelaySeconds: 0
    # -- Period seconds for livenessProbe
    periodSeconds: 10
    # -- Timeout seconds for livenessProbe
    timeoutSeconds: 1
    # -- Failure threshold for livenessProbe
    failureThreshold: 3
    # -- Success threshold for livenessProbe
    successThreshold: 1
    httpGet:
      path: /
      port: http

  readinessProbe:
    # -- Enable readinessProbe on prusaExporter containers
    enabled: true
    # -- Initial delay seconds for readinessProbe
    initialDelaySeconds: 0
    # -- Period seconds for readinessProbe
    periodSeconds: 10
    # -- Timeout seconds for readinessProbe
    timeoutSeconds: 1
    # -- Failure threshold for readinessProbe
    failureThreshold: 3
    # -- Success threshold for readinessProbe
    successThreshold: 1
    httpGet:
      path: /
      port: http

  startupProbe:
    # -- Enable startupProbe on prusaExporter containers
    enabled: false
    # -- Initial delay seconds for startupProbe
    initialDelaySeconds: 0
    # -- Period seconds for startupProbe
    periodSeconds: 10
    # -- Timeout seconds for startupProbe
    timeoutSeconds: 1
    # -- Failure threshold for startupProbe
    failureThreshold: 3
    # -- Success threshold for startupProbe
    successThreshold: 1
    httpGet:
      path: /
      port: http
  
  # -- Custom livenessProbe that overrides the default one
  customLivenessProbe: {}
  # -- Custom readinessProbe that overrides the default one
  customReadinessProbe: {}
  # -- Custom startupProbe that overrides the default one
  customStartupProbe: {}
  ## prusaExporter resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  # -- Set prusaExporter container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if prusaExporter.resources is set (prusaExporter.resources is recommended for production).
  # More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  resourcesPreset: "nano"
  # -- Set prusaExporter container requests and limits for different resources like CPU or memory (essential for production workloads)
  resources: {}
  ## e.g:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##

  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  podSecurityContext:
    # -- Enable prusaExporter pods' Security Context
    enabled: true
    # -- Set filesystem group change policy for prusaExporter pods
    fsGroupChangePolicy: Always
    # -- settings using the sysctl interface for prusaExporter pods
    sysctls: []
    # -- Set filesystem extra groups for prusaExporter pods
    supplementalGroups: []
    # -- Set fsGroup in prusaExporter pods' Security Context
    fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  containerSecurityContext:
    # -- Enabled prusaExporter container' Security Context
    enabled: true
    # -- Set SELinux options in prusaExporter container
    seLinuxOptions: {}
    # -- Set runAsUser in prusaExporter container' Security Context
    runAsUser: 1001
    runAsGroup: 1001
    # -- Set runAsNonRoot in prusaExporter container' Security Context
    runAsNonRoot: true
    # -- Set readOnlyRootFilesystem in prusaExporter container' Security Context
    readOnlyRootFilesystem: true
    # -- Set privileged in prusaExporter container' Security Context
    privileged: false
    # -- Set allowPrivilegeEscalation in prusaExporter container' Security Context
    allowPrivilegeEscalation: false
    # -- List of capabilities to be dropped in prusaExporter container
    capabilities:
      drop: ["ALL"]
    # -- Set seccomp profile in prusaExporter container
    seccompProfile:
      type: "RuntimeDefault"
    
  # -- Override default prusaExporter container command (useful when using custom images)
  command: []
  # -- Override default prusaExporter container args (useful when using custom images)
  args:
    - '--config.file=/config/prusa.yml'
    - '--log.level=info'
    - '--prusalink.scrape-timeout=5'
  # -- Mount Service Account token in prusaExporter pods
  automountServiceAccountToken: false
  # -- Annotations for prusaExporter
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}
  # -- prusaExporter pods host aliases
  # ref: https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  hostAliases: []

  # -- Extra labels for prusaExporter pods
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}
  # -- Annotations for prusaExporter pods
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # -- Pod affinity preset. Ignored if `prusaExporter.affinity` is set. Allowed values: `soft` or `hard`
  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAffinityPreset: ""
  # -- Pod anti-affinity preset. Ignored if `prusaExporter.affinity` is set. Allowed values: `soft` or `hard`
  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  podAntiAffinityPreset: soft
  ## Node prusaExporter.affinity preset
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
  nodeAffinityPreset:
    # -- Node affinity preset type. Ignored if `prusaExporter.affinity` is set. Allowed values: `soft` or `hard`
    type: ""
    # -- Node label key to match. Ignored if `prusaExporter.affinity` is set
    key: ""
    # -- Node label values to match. Ignored if `prusaExporter.affinity` is set
    values: []
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
  # -- Affinity for prusaExporter pods assignment
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # NOTE: `prusaExporter.podAffinityPreset`, `prusaExporter.podAntiAffinityPreset`, and `prusaExporter.nodeAffinityPreset` will be ignored when it's set
  affinity: {}
  # -- Node labels for prusaExporter pods assignment
  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  nodeSelector: {}
  # --Tolerations for prusaExporter pods assignment
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
  # -- Deployment strategy type
  # ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  updateStrategy:
    ## ONLY FOR DEPLOYMENTS:
    ## Can be set to RollingUpdate or Recreate
    ## ONLY FOR STATEFULSETS:
    ## Can be set to RollingUpdate or OnDelete
    ##
    type: RollingUpdate
  # -- Seconds prusaExporter pods need to terminate gracefully
  # ref: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
  terminationGracePeriodSeconds: ""
  # -- Array with extra environment variables to add to prusaExporter containers
  extraEnvVars: []
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##

  # -- Name of existing ConfigMap containing extra env vars for prusaExporter containers
  extraEnvVarsCM: ""
  # -- Name of existing Secret containing extra env vars for prusaExporter containers
  extraEnvVarsSecret: ""
  # -- Optionally specify extra list of additional volumes for the prusaExporter pods
  extraVolumes: []
  # -- Optionally specify extra list of additional volumeMounts for the prusaExporter containers
  extraVolumeMounts: []
  # -- Add additional sidecar containers to the prusaExporter pods
  sidecars: []
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##

  # -- Add additional init containers to the prusaExporter pods
  # ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  initContainers: []
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##

services:
  prusaExporter:
    # -- The service type
    type: ClusterIP
    
    ports:
      - name: http
        port: 10009
        protocol: TCP
    # -- prusaExporter service Cluster IP
    clusterIP: ""
    ## e.g.:
    ## clusterIP: None

    # -- prusaExporter service Load Balancer IP
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
    loadBalancerIP: ""
    # -- prusaExporter service Load Balancer sources
    # ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
    loadBalancerSourceRanges: []
    ## e.g:
    ## loadBalancerSourceRanges:
    ##   - 10.10.10.0/24
    ##

    # -- prusaExporter service external traffic policy
    # ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    externalTrafficPolicy: Cluster
    # -- Additional custom annotations for prusaExporter service
    annotations: {}
    # -- Extra ports to expose in prusaExporter service (normally used with the `sidecars` value)
    extraPorts: []
    # -- Control where client requests go, to the same pod or round-robin
    # Values: ClientIP or None
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/
    sessionAffinity: None
    # -- Additional settings for the sessionAffinity
    sessionAffinityConfig: {}
    ## e.g:
    ## sessionAffinityConfig:
    ##   clientIP:
    ##     timeoutSeconds: 300
    ##
  prusaExporterPrusalink:
    # -- The service type
    type: LoadBalancer
    
    ports:
      - name: prusalink
        port: 8514
        protocol: UDP
    # -- prusaExporterPrusalink service Cluster IP
    clusterIP: ""
    ## e.g.:
    ## clusterIP: None

    # -- prusaExporterPrusalink service Load Balancer IP
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
    loadBalancerIP: ""
    # -- prusaExporterPrusalink service Load Balancer sources
    # ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
    loadBalancerSourceRanges: []
    ## e.g:
    ## loadBalancerSourceRanges:
    ##   - 10.10.10.0/24
    ##

    # -- prusaExporterPrusalink service external traffic policy
    # ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    externalTrafficPolicy: Cluster
    # -- Additional custom annotations for prusaExporterPrusalink service
    annotations: {}
    # -- Extra ports to expose in prusaExporterPrusalink service (normally used with the `sidecars` value)
    extraPorts: []
    # -- Control where client requests go, to the same pod or round-robin
    # Values: ClientIP or None
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/
    sessionAffinity: None
    # -- Additional settings for the sessionAffinity
    sessionAffinityConfig: {}
    ## e.g:
    ## sessionAffinityConfig:
    ##   clientIP:
    ##     timeoutSeconds: 300
    ##

## ServiceAccount configuration
##
serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: true
  # -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the common.names.fullname template
  name: ""
  # -- Additional Service Account annotations (evaluated as a template)
  annotations: {}
  # -- Automount service account token for the server service account
  automountServiceAccountToken: true
  

## Secrets
prusaExporterSecret:
  prusa: ""
  existingSecret: ""



metrics:
  enabled: false
  serviceMonitors:
    prusaExporter:
      # -- If `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)
      enabled: false
      # -- Namespace in which Prometheus is running.
      namespace: ""
      #--  Additional custom annotations for the ServiceMonitor
      annotations: {}
      # -- Extra labels for the ServiceMonitor
      labels: {}
      # -- The name of the label on the target service to use as the job name in Prometheus
      jobLabel: ""
      # -- honorLabels chooses the metric's labels on collisions with target labels
      honorLabels: false
      # -- Interval at which metrics should be scraped.
      # ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
      interval: ""
      ## e.g:
      ## interval: 10s
      ##

      # -- Timeout after which the scrape is ended
      # ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
      scrapeTimeout: ""
      ## e.g:
      ## scrapeTimeout: 10s
      ##

      # -- Specify additional relabeling of metrics
      metricRelabelings: []
      # -- Specify general relabeling
      relabelings: []
      # -- Prometheus instance selector labels
      # ref: https://github.com/bitnami/charts/tree/main/bitnami/prometheus-operator#prometheus-configuration
      selector: {}
      ## selector:
      ##   prometheus: my-prometheus
      ##
  
