{{- if not .Values.nextcloud.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.redis.secretName" . }}
type: Opaque
data:
  password: {{ .Values.nextcloud.redis.password | b64enc | quote }}
{{- end }}
