apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ping-exporter.fullname" . }}-config
data:
  config.yml: |-
    targets:
    {{- range .Values.targets }}
    - {{ . | quote }}
    {{- end }}
