---
# -- The target IP and port of the apcupsd service to scrape.
target: ""

antiAffinity: false

apcupsd-exporter:
  image:
    repository: thelande/apcupsd_exporter
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}

metrics:
  # -- Enable the ServiceMonitor resource. Requires that the ServiceMonitor CRD
  # exists within your cluster.
  enabled: false
  apcupsd-exporter:
    interval: 30s
    timeout: 10s
