apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmeteo-exporter.fullname" . }}-config
  labels:
    {{- include "openmeteo-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    locations:
      {{- toYaml .Values.locations | nindent 10 }}
