{{- if and .Values.serviceMonitor.enabled .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "apcupsd-exporter.fullname" . }}
  labels:
    {{- include "apcupsd-exporter.labels" . | nindent 4 }}
spec:
  {{ .Files.Get "alert-rules.yaml" }}
{{- end }}
