# Copyright Thomas Helander. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Office
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Excellent file management and collaboration for public authorities, providers and business - or anyone who values ease of use and digital sovereignty.
home: https://opencloud.eu/
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/opencloud.png
maintainers:
  - name: Tom Helander
    url: https://github.com/thelande/charts
name: opencloud
sources:
  - https://github.com/thelande/charts/tree/main/charts/opencloud
  - https://github.com/opencloud-eu/opencloud
version: 0.1.1
