apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docmost.fullname" . }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docmost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "docmost.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "docmost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -c
            - |
              export DATABASE_URL="postgresql://${PGSQL_DB_USERNAME}:${PGSQL_DB_PASSWORD}@${PGSQL_DB_HOST}/${PGSQL_DB_NAME}?schema=public{{ .Values.postgres.sslMode }}{{ .Values.postgres.extraParams }}"
              pnpm start
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PGSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.appSecretName }}
                  key: host
            - name: PGSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.appSecretName }}
                  key: dbname
            - name: PGSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.appSecretName }}
                  key: username
            - name: PGSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.appSecretName }}
                  key: password
            - name: APP_URL
              value: {{ (required "An app URL is required" .Values.docmost.appUrl) | quote }}
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "docmost.appSecret.secretName" . }}
                  key: appSecret
            - name: REDIS_URL
              value: {{ (required "A redis URL is required" .Values.redis.url) | quote }}
            {{- if .Values.docmost.debugMode }}
            - name: DEBUG_MODE
              value: "true"
            {{- end }}
            {{- if .Values.docmost.storage.driver }}
            - name: STORAGE_DRIVER
              value: {{ .Values.docmost.storage.driver | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.region }}
            - name: AWS_S3_REGION
              value: {{ .Values.docmost.storage.s3.region | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.bucket }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.docmost.storage.s3.bucket | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.endpoint }}
            - name: AWS_S3_ENDPOINT
              value: {{ .Values.docmost.storage.s3.endpoint | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.url }}
            - name: AWS_S3_URL
              value: {{ .Values.docmost.storage.s3.url | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.forcePathStyle }}
            - name: AWS_S3_FORCE_PATH_STYLE
              value: {{ .Values.docmost.storage.s3.forcePathStyle | quote }}
            {{- end }}
            {{- if .Values.docmost.storage.s3.existingSecret }}
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.docmost.storage.s3.existingSecret }}
                  key: access-key-id
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.docmost.storage.s3.existingSecret }}
                  key: secret-access-key
            {{- else if .Values.docmost.storage.s3.accessKeyId }}
            - name: AWS_S3_ACCESS_KEY_ID
              value: {{ .Values.docmost.storage.s3.accessKeyId | quote }}
            - name: AWS_S3_SECRET_ACCESS_KEY
              value: {{ .Values.docmost.storage.s3.secretAccessKey | quote }}
            {{- end }}
            {{- if .Values.docmost.fileUploadSizeLimit }}
            - name: FILE_UPLOAD_SIZE_LIMIT
              value: {{ .Values.docmost.fileUploadSizeLimit | quote }}
            {{- end }}
            {{- if .Values.docmost.fileImportSizeLimit }}
            - name: FILE_IMPORT_SIZE_LIMIT
              value: {{ .Values.docmost.fileImportSizeLimit | quote }}
            {{- end }}
            {{- if .Values.docmost.drawIO.url }}
            - name: DRAWIO_URL
              value: {{ .Values.docmost.drawIO.url | quote }}
            {{- end }}
            {{- if .Values.docmost.oidc.buttonText }}
            - name: OIDC_BUTTON_TEXT
              value: {{ .Values.docmost.oidc.buttonText | quote }}
            {{- end }}
            {{- if .Values.docmost.oidc.autoRedirect }}
            - name: OIDC_AUTO_REDIRECT
              value: "true"
            {{- end }}
            {{- if .Values.docmost.jwtTokenExpiresIn }}
            - name: JWT_TOKEN_EXPIRES_IN
              value: {{ .Values.docmost.jwtTokenExpiresIn | quote }}
            {{- end }}
            {{- if .Values.docmost.databaseMaxPool }}
            - name: DATABASE_MAX_POOL
              value: {{ .Values.docmost.databaseMaxPool | quote }}
            {{- end }}
            {{- if .Values.docmost.disableTelemetry }}
            - name: DISABLE_TELEMETRY
              value: "true"
            {{- end }}
            {{- if .Values.docmost.port }}
            - name: PORT
              value: {{ .Values.docmost.port | quote }}
            {{- end }}
            {{- if .Values.docmost.posthogHost }}
            - name: POSTHOG_HOST
              value: {{ .Values.docmost.posthogHost | quote }}
            {{- end }}
            {{- if .Values.docmost.posthogKey }}
            - name: POSTHOG_KEY
              value: {{ .Values.docmost.posthogKey | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.docmost.smtp.enabled }}
            - name: MAIL_DRIVER
              value: smtp
            - name: SMTP_HOST
              value: {{ (required "SMTP host is required." .Values.docmost.smtp.host) | quote }}
            - name: SMTP_PORT
              value: {{ .Values.docmost.smtp.port | quote }}
            - name: SMTP_SECURE
              value: {{ .Values.docmost.smtp.secure | quote }}
            {{- if .Values.docmost.smtp.ignoreTls }}
            - name: SMTP_IGNORETLS
              value: "true"
            {{- end }}
            {{- if .Values.docmost.postmark.token }}
            - name: MAIL_DRIVER
              value: postmark
            - name: POSTMARK_TOKEN
              value: {{ .Values.docmost.postmark.token | quote }}
            {{- end }}
            - name: MAIL_FROM_ADDRESS
              value: {{ (required "Mail from address is required." .Values.docmost.smtp.mailFrom.address) | quote }}
            - name: MAIL_FROM_NAME
              value: {{ (required "Mail from name is required." .Values.docmost.smtp.mailFrom.name) | quote }}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "docmost.smtp.auth.secretName" . }}
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "docmost.smtp.auth.secretName" . }}
                  key: password
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /app/data/storage
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "docmost.persistence.existingClaim" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
