{{- if not .Values.owncloud.admin.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "owncloud.admin.secretName" . }}
data:
  username: {{ .Values.owncloud.admin.username | b64enc }}
  password: {{ .Values.owncloud.admin.password | b64enc }}
{{- end }}
