apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "owncloud.fullname" . }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "owncloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "owncloud.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "owncloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      env:
        - name: OWNCLOUD_DOMAIN
          value: {{ .Values.owncloud.domain | quote }}
        - name: OWNCLOUD_TRUSTED_DOMAINS
          value: {{ (join "," .Values.owncloud.trustedDomains) | quote }}
        - name: OWNCLOUD_DB_TYPE
          value: pgsql
        - name: OWNCLOUD_DB_HOST
          value: postgres-cluster-rw
        - name: OWNCLOUD_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-cluster-app
              key: dbname
        - name: OWNCLOUD_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-cluster-app
              key: username
        - name: OWNCLOUD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-cluster-app
              key: password
        - name: OWNCLOUD_REDIS_ENABLED
          value: "true"
        - name: OWNCLOUD_REDIS_HOST
          value: redis-leader
        - name: OWNCLOUD_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "owncloud.admin.secretName" . }}
              key: username
        - name: OWNCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "owncloud.admin.secretName" . }}
              key: password
      {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
