{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "owncloud.fullname" . }}-data
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    {{- toYaml .Values.persistence.resources | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
